### PR TITLE
Add documentation for new distutils plugin properties.

### PR DESCRIPTION
**Pull request by BackroomGibbon**
Added documentation for the following properties:

- distutils_upload_repository
- distutils_upload_sign
- distutils_upload_sign_identity

### CODE REVIEW

**Comment by esc** [comment]
Do we have an automatic preview build of the docs ready anywhere?

**Comment by esc** [comment]
Anyway, LGTM.

**Comment by esc** [comment]
@BackroomGibbon thanks again for the contribution, the site is already live and the changes look good.

**Comment by BackroomGibbon** [comment]
No worries, glad I could help.

**Comment by mriehl** [comment]
@esc GH Pages doesn't have a preview feature. I can add travis CI so that the static content is built. But we would have to upload it "somewhere". I guess S3 would work but it  seems to be too much work given that github already provides a rendered markdown preview.

My stance on this is to basically always merge documentation PRs. If it needs some tuning I do it afterwards. For big overhauls I pull manually and run `jekyll server`

**Comment by esc** [comment]
yeah, we should ask github to provide such a feature!

**Pull request merged**
